services:
  s3like:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "s3like"
    image: "s3like:latest"
    ports:
      - "9080:9080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=${DB_SSLMODE}
      - JWT_SECRET=${JWT_SECRET}
      - STORAGE_PATH=${STORAGE_PATH}
      - SERVER_PORT=${SERVER_PORT}
    volumes:
      - ./storage:/storage
